=== RunedUniverse/r4m-maven-extension/model/src/main/resources/r4m-pem-v1_1_0.xsd
<?xml version="1.0"?>
<!--

    Copyright Â© 2024 VenaNocta (venanocta@gmail.com)

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="https://api.runeduniverse.net/runes4tools/r4m-pem"
	xmlns="https://api.runeduniverse.net/runes4tools/r4m-pem"
	elementFormDefault="qualified">
	<xs:element name="project-execution-model" type="Model" />
	<xs:complexType name="Model">
		<xs:all>
			<xs:element name="modelVersion" type="AnyId"
				default="1.1.0" />
			<xs:element name="executions">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="execution" type="Execution"
							minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="Execution">
		<xs:all>
			<xs:element name="inherited" default="true" minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						Whether the execution should be propagated to
						downstream projects.
					</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true" />
						<xs:enumeration value="false" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="restrictions"
				type="ExecutionRestrictions" minOccurs="0" />
			<xs:element name="triggers" type="ExecutionTriggers"
				minOccurs="0" />
			<xs:element name="lifecycles" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="lifecycle" type="Lifecycle"
							minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="id" type="ExecutionId" use="required" />
		<xs:attribute name="source" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="override" />
					<xs:enumeration value="workflow" />
					<xs:enumeration value="packaging" />
					<xs:enumeration value="plugin" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="ExecutionRestrictions">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="packaging-procedure" type="PackagingId">
					<xs:annotation>
						<xs:documentation>
							Used to select packaging flag in POM. Keep in
							mind the POM's packaging flag only indirectly defines the
							Artifacts Type.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:any namespace="##other">
					<xs:annotation>
						<xs:documentation>
							Other extensions may provide additional
							restrictions.
						</xs:documentation>
					</xs:annotation>
				</xs:any>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ExecutionTriggers">
		<xs:choice>
			<xs:element name="always" minOccurs="0" maxOccurs="1" />
			<xs:element name="never" minOccurs="0" maxOccurs="1" />
			<xs:sequence>
				<xs:element name="default" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>
							Execute when explicitly specified or no other
							Execution got explicitly specified via maven '@execution-id'.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="on-call" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>
							Execute when explicitly called by via maven
							'@execution-id'.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="active-profile" type="Profile">
						<xs:annotation>
							<xs:documentation>
								Trigger is successful when the Profile got
								explicitly mentioned by executing 'mvn -Pactive-profile'.
							</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="inactive-profile" type="Profile">
						<xs:annotation>
							<xs:documentation>
								Trigger is successful when the Profile was
								defined somewhere in the POM hierarchy and was not explicitly
								mentioned to maven.
							</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="provided-profile" type="Profile">
						<xs:annotation>
							<xs:documentation>
								Trigger is successful when the Profile was
								defined somewhere in the POM hierarchy.
							</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="missing-profile" type="Profile">
						<xs:annotation>
							<xs:documentation>
								Trigger is successful when the Profile was
								neither explicitly mentioned to maven nor defined somewhere in
								the POM hierarchy.
							</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:any namespace="##other">
						<xs:annotation>
							<xs:documentation>
								Other extensions may provide additional
								triggers.
							</xs:documentation>
						</xs:annotation>
					</xs:any>
				</xs:choice>
			</xs:sequence>
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="Profile">
		<xs:attribute name="id" type="AnyId" use="required" />
	</xs:complexType>

	<xs:complexType name="Lifecycle">
		<xs:all>
			<xs:element name="phases" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="phase" type="Phase" minOccurs="0"
							maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="id" type="LifecycleId" use="required" />
	</xs:complexType>

	<xs:complexType name="Phase">
		<xs:all>
			<xs:element name="goals" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="goal" type="Goal" minOccurs="0"
							maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="id" type="PhaseId" use="required" />
	</xs:complexType>

	<xs:complexType name="Goal">
		<xs:all>
			<xs:element name="groupId" type="ArtifactGroupId" />
			<xs:element name="artifactId" type="AnyId" />
			<xs:element name="modes">
				<xs:complexType>
					<xs:sequence>
						<xs:choice minOccurs="1" maxOccurs="unbounded">
							<xs:element name="mode" type="Mode" />
							<xs:any namespace="##other" />
						</xs:choice>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="fork" type="Fork" minOccurs="0" />
		</xs:all>
		<xs:attribute name="id" type="AnyId" use="required" />
		<xs:attribute name="optional" use="optional"
			default="true">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="true" />
					<xs:enumeration value="false" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="Mode">
		<xs:attribute name="id" type="ModeId" use="required">
			<xs:annotation>
				<xs:documentation>
					Select the id under which this goal should be
					activated, examples are 'default' and 'dev' but you may select any
					string without whitespace characters.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="Fork">
		<xs:all>
			<xs:element name="mode" type="Mode" minOccurs="0"
				maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						Mode under which the forked Executions will be
						executed.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="executions" type="TargetExecutions"
				minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						Defined Executions will be inherited by all
						phases.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="lifecycle" type="TragetLifecycle"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="phases" type="TragetPhases"
				minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						Defined Phases will be executed in order of
						definition. These phases will override definitions
						phase-execution
						restrictions inside of lifecycle definition.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="excludedPhases"
				type="TargetExcludedPhases" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						Defined Phases will be removed from Lifecycle
						definitions and Phase definitions. In case Executions are
						defined,
						the defined Executions will be removed from predefined
						Phases.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="TragetLifecycle">
		<xs:all>
			<xs:element name="startPhase" type="PhaseId" minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						Start-Phase at which to start executing.
						Start-Phases not defined in Lifecycle will be ignored!
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="stopPhase" type="PhaseId" minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						Stop-Phase at which to stop executing.
						Stop-Phases not defined in Lifecycle will be ignored!
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:all>
		<xs:attribute name="id" type="LifecycleId" use="required" />
	</xs:complexType>

	<xs:complexType name="TragetPhases">
		<xs:sequence>
			<xs:element name="phase" minOccurs="0"
				maxOccurs="unbounded">
				<xs:complexType>
					<xs:all>
						<xs:element name="executions" minOccurs="0"
							type="TargetExecutions">
							<xs:annotation>
								<xs:documentation>
									Defined Executions will only be activated in
									the Phase they are
									defined in.
								</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:all>
					<xs:attribute name="id" type="PhaseId" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="TargetExcludedPhases">
		<xs:sequence>
			<xs:element name="phase" minOccurs="0"
				maxOccurs="unbounded">
				<xs:complexType>
					<xs:all>
						<xs:element name="executions" minOccurs="0"
							type="TargetExecutions">
							<xs:annotation>
								<xs:documentation>
									Defined Executions will be removed from
									predefined Phases. Phases with
									no remaining active executions
									will be skipped.
								</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:all>
					<xs:attribute name="id" type="PhaseId" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="TargetExecutions">
		<xs:sequence>
			<xs:element name="execution" minOccurs="0"
				maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="id" type="ExecutionId"
						use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="AnyId">
		<xs:restriction base="xs:string">
			<xs:pattern value="\s*\S+\s*" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PackagingId">
		<xs:union memberTypes="AnyId">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="pom" />
					<xs:enumeration value="jar" />
					<xs:enumeration value="maven-plugin" />
					<xs:enumeration value="ejb" />
					<xs:enumeration value="war" />
					<xs:enumeration value="ear" />
					<xs:enumeration value="rar" />
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="ExecutionId">
		<xs:union memberTypes="AnyId">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="default" />
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="LifecycleId">
		<xs:union memberTypes="AnyId">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="default" />
					<xs:enumeration value="clean" />
					<xs:enumeration value="site" />
					<xs:enumeration value="help" />
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="PhaseId">
		<xs:union memberTypes="AnyId">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<!-- Clean Lifecycle -->
					<xs:enumeration value="pre-clean" />
					<xs:enumeration value="clean" />
					<xs:enumeration value="post-clean" />
					<!-- Default Lifecycle -->
					<xs:enumeration value="validate" />
					<xs:enumeration value="initialize" />
					<xs:enumeration value="generate-sources" />
					<xs:enumeration value="process-sources" />
					<xs:enumeration value="generate-resources" />
					<xs:enumeration value="process-resources" />
					<xs:enumeration value="compile" />
					<xs:enumeration value="process-classes" />
					<xs:enumeration value="generate-test-sources" />
					<xs:enumeration value="process-test-sources" />
					<xs:enumeration value="generate-test-resources" />
					<xs:enumeration value="process-test-resources" />
					<xs:enumeration value="test-compile" />
					<xs:enumeration value="process-test-classes" />
					<xs:enumeration value="test" />
					<xs:enumeration value="prepare-package" />
					<xs:enumeration value="package" />
					<xs:enumeration value="pre-integration-test" />
					<xs:enumeration value="integration-test" />
					<xs:enumeration value="post-integration-test" />
					<xs:enumeration value="verify" />
					<xs:enumeration value="install" />
					<xs:enumeration value="deploy" />
					<!-- Site Lifecycle -->
					<xs:enumeration value="pre-site" />
					<xs:enumeration value="site" />
					<xs:enumeration value="post-site" />
					<xs:enumeration value="site-deploy" />
					<!-- R4M - Help Lifecycle -->
					<xs:enumeration value="help" />
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="ModeId">
		<xs:union memberTypes="AnyId">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="default" />
					<xs:enumeration value="dev" />
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="ArtifactGroupId">
		<xs:union memberTypes="AnyId">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="org.apache.maven.plugins" />
					<xs:enumeration value="org.codehaus.mojo" />
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>

</xs:schema>

=== RunedUniverse/r4m-maven-extension/model/src/main/resources/pem.xml
<!--

    Copyright Â© 2024 VenaNocta (venanocta@gmail.com)

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<!-- <project-execution-model xmlns="https://api.runeduniverse.net/runes4tools/r4m-pem" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://api.runeduniverse.net/runes4tools/r4m-pem 
	https://api.runeduniverse.net/runes4tools/r4m-pem-v1_0_0.xsd"> -->
<project-execution-model
	xmlns="https://api.runeduniverse.net/runes4tools/r4m-pem"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://api.runeduniverse.net/runes4tools/r4m-pem r4m-pem-v1_1_0.xsd">

	<modelVersion>1.1.0</modelVersion>
	<executions>

		<execution id="default" source="override">
			<triggers>
				<always />
			</triggers>
			<lifecycles>
				<lifecycle id="default">
					<phases>
						<phase id="compile">
							<goals>
								<goal id="compiler-summary">
									<modes>
										<mode id="default"/>
										<mode id="dev"/>
									</modes>
									<groupId>net.runeduniverse.tools.maven.r4m</groupId>
									<artifactId>r4m-maven-extension</artifactId>
									<fork>
										<mode id="default"/>
										<executions>
											<execution id="default" />
										</executions>
										<lifecycle id="compiler" />
									</fork>
								</goal>
							</goals>
						</phase>
						<phase id="test-compile">
							<goals>
								<goal id="compiler-summary" optional="true">
									<modes>
										<mode id="default"/>
										<mode id="dev"/>
									</modes>
									<groupId>net.runeduniverse.tools.maven.r4m</groupId>
									<artifactId>r4m-maven-extension</artifactId>
									<fork>
										<mode id="default"/>										
										<executions>
											<execution id="test" />
										</executions>
										<lifecycle id="compiler" />
									</fork>
								</goal>
							</goals>
						</phase>
					</phases>
				</lifecycle>
			</lifecycles>
		</execution>

	</executions>
</project-execution-model>
